# Parameters used to generate this project with aem-project-archetype

groupId=com.brainvire.aem
artifactId=brainvire-demo-site
version=0.0.1-SNAPSHOT
package=com.brainvire.aem.brainviredemosite
appId=brainvire-demo-site
appTitle=Brainvire Demo Site
aemVersion=cloud
sdkVersion=latest
languageCountry=${languageCountry}
includeExamples=n
includeErrorHandler=n
frontendModule=general
singleCountry=n
includeDispatcherConfig=y
includeCif=n
includeForms=n
includeFormsenrollment=n
includeFormscommunications=n
sdkFormsVersion=latest
commerceEndpoint=https://hostname.com/graphql
datalayer=y
amp=n
enableDynamicMedia=n
precompiledScripts=n
includeFormsheadless=n
